version: 2
updates:
  # Track in case we ever add dependencies.
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'

  # Keep example and test/benchmark deps up-to-date.
  - package-ecosystem: 'gomod'
    directories:
      - '/internal/examples'
      - '/internal/thirdparty'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore'
    labels: []
    groups:
      internal-deps:
        patterns:
          - '*'
