// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package websocket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataText-1]
	_ = x[DataBinary-2]
}

const _DataType_name = "TextBinary"

var _DataType_index = [...]uint8{0, 4, 10}

func (i DataType) String() string {
	i -= 1
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
