// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package ws

import "strconv"

const _DataFrame_name = "TextBinary"

var _DataFrame_index = [...]uint8{0, 4, 10}

func (i DataType) String() string {
	i -= 1
	if i < 0 || i >= DataType(len(_DataFrame_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataFrame_name[_DataFrame_index[i]:_DataFrame_index[i+1]]
}
