// Code generated by "stringer -type=opCode"; DO NOT EDIT.

package ws

import "strconv"

const (
	_opCode_name_0 = "opContinuationopTextopBinary"
	_opCode_name_1 = "opCloseopPingopPong"
)

var (
	_opCode_index_0 = [...]uint8{0, 14, 20, 28}
	_opCode_index_1 = [...]uint8{0, 7, 13, 19}
)

func (i opCode) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _opCode_name_0[_opCode_index_0[i]:_opCode_index_0[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _opCode_name_1[_opCode_index_1[i]:_opCode_index_1[i+1]]
	default:
		return "opCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
