// Code generated by "stringer -type=StatusCode"; DO NOT EDIT.

package ws

import "strconv"

const _StatusCode_name = "StatusNormalClosureStatusGoingAwayStatusProtocolErrorStatusUnsupportedData"

var _StatusCode_index = [...]uint8{0, 19, 34, 53, 74}

func (i StatusCode) String() string {
	i -= 1000
	if i < 0 || i >= StatusCode(len(_StatusCode_index)-1) {
		return "StatusCode(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[i]:_StatusCode_index[i+1]]
}
