// Code generated by "stringer -type=StatusCode"; DO NOT EDIT.

package ws

import "strconv"

const (
	_StatusCode_name_0 = "StatusNormalClosureStatusGoingAwayStatusProtocolErrorStatusUnsupportedData"
	_StatusCode_name_1 = "StatusNoStatusRcvdStatusAbnormalClosureStatusInvalidFramePayloadDataStatusPolicyViolationStatusMessageTooBigStatusMandatoryExtStatusInternalErrorStatusServiceRestartStatusTryAgainLaterStatusBadGatewayStatusTLSHandshake"
)

var (
	_StatusCode_index_0 = [...]uint8{0, 19, 34, 53, 74}
	_StatusCode_index_1 = [...]uint8{0, 18, 39, 68, 89, 108, 126, 145, 165, 184, 200, 218}
)

func (i StatusCode) String() string {
	switch {
	case 1000 <= i && i <= 1003:
		i -= 1000
		return _StatusCode_name_0[_StatusCode_index_0[i]:_StatusCode_index_0[i+1]]
	case 1009 <= i && i <= 1019:
		i -= 1009
		return _StatusCode_name_1[_StatusCode_index_1[i]:_StatusCode_index_1[i+1]]
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
