// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package wscore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpContinuation-0]
	_ = x[OpText-1]
	_ = x[OpBinary-2]
	_ = x[OpClose-11]
	_ = x[OpPing-12]
	_ = x[OpPong-13]
}

const (
	_Opcode_name_0 = "OpContinuationOpTextOpBinary"
	_Opcode_name_1 = "OpCloseOpPingOpPong"
)

var (
	_Opcode_index_0 = [...]uint8{0, 14, 20, 28}
	_Opcode_index_1 = [...]uint8{0, 7, 13, 19}
)

func (i Opcode) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Opcode_name_0[_Opcode_index_0[i]:_Opcode_index_0[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _Opcode_name_1[_Opcode_index_1[i]:_Opcode_index_1[i+1]]
	default:
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
