FROM golang:1.12

LABEL "com.github.actions.name"="go fmt"
LABEL "com.github.actions.description"="Ensure files are formatted"
LABEL "com.github.actions.icon"="code"
LABEL "com.github.actions.color"="purple"

CMD gofmt -l -s .
