FROM golang:1.12

LABEL "com.github.actions.name"="go test"
LABEL "com.github.actions.description"="Ensure code works"
LABEL "com.github.actions.icon"="code"
LABEL "com.github.actions.color"="purple"

COPY entrypoint.sh /entrypoint.sh

CMD ["/entrypoint.sh"]
