FROM golang:1.12

LABEL "com.github.actions.name"="fmt"
LABEL "com.github.actions.description"="fmt"
LABEL "com.github.actions.icon"="code"
LABEL "com.github.actions.color"="purple"

COPY entrypoint.sh /entrypoint.sh

CMD ["/entrypoint.sh"]
