#!/bin/sh
set -eu
cd -- "$(dirname "$0")/.."

go vet ./...
GOOS=js GOARCH=wasm go vet ./...

go install golang.org/x/lint/golint@latest
golint -set_exit_status ./...
GOOS=js GOARCH=wasm golint -set_exit_status ./...

go install honnef.co/go/tools/cmd/staticcheck@latest
staticcheck ./...
GOOS=js GOARCH=wasm staticcheck ./...
